NotImplemented_MSG = "Method Not Implemented"
NoRadius_MSG = "'self' does not have a radius attribute."
NoWidthHeight_MSG = "'self' does not have a width and height attribute."
TypeError_MSG = "Type Error"
ValueError_MSG = "Value Error"
